In [45]:
#Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from sklearn.datasets import load_files
import nltk
import pickle
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split  
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


from sklearn.feature_extraction.text import CountVectorizer

nltk.download('stopwords')
#stopwords.words('english')[0:20]


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/mourad/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [21]:
#Load the datasets
emailDataSet = load_files('./datasets/')
X,y=emailDataSet.data,emailDataSet.target

In [22]:
len(y)

3052

In [26]:
#processing
stemmer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /Users/mourad/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [27]:
documents = []

for sen in range(0, len(X)):  
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))

    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)

    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)

    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)

    # Converting to Lowercase
    document = document.lower()

    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)

    documents.append(document)


In [47]:
documents[0]

'from rpm list admin freshrpms net mon aug 26 15 21 33 2002 nreturn path rpm zzzlist admin freshrpms net ndelivered to yyyy localhost netnoteinc com nreceived from localhost localhost 127 0 0 1 tby phobos lab netnoteinc com postfix with esmtp id 35de544174 tfor jm localhost mon 26 aug 2002 10 17 46 0400 edt nreceived from phobos 127 0 0 1 tby localhost with imap fetchmail 5 9 0 tfor jm localhost single drop mon 26 aug 2002 15 17 46 0100 ist nreceived from egwn net ns2 egwn net 193 172 5 4 by dogma slashnull org 8 11 6 8 11 6 with esmtp id g7p0glz25869 for jm rpm jmason org sun 25 aug 2002 01 42 47 0100 nreceived from auth02 nl egwn net localhost 127 0 0 1 by egwn net 8 11 6 8 11 6 egwn with esmtp id g7p0f2j13996 sun 25 aug 2002 02 41 02 0200 nreceived from imf17bis bellsouth net mail217 mail bellsouth net 205 152 58 157 by egwn net 8 11 6 8 11 6 egwn with esmtp id g7p0eej05587 for rpm list freshrpms net sun 25 aug 2002 02 40 14 0200 nreceived from adsl 157 17 129 msy bellsouth net 66 1

In [31]:
#To see the number of features
vectorizer = CountVectorizer(min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()
print(len(X[0]))
print(X)
feature_list = vectorizer.get_feature_names()
feature_list

11009
[[0 0 1 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [4 0 4 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


['00',
 '000',
 '0000',
 '000000',
 '000066',
 '000080',
 '000099',
 '0000cc',
 '0000ff',
 '0001',
 '00039344ddd6',
 '00039396ecf2',
 '000393a46dea',
 '00260600',
 '0030657c53ea',
 '003065c182b0',
 '003065f62cd6',
 '003065f93d3a',
 '003399',
 '004',
 '005',
 '006600',
 '007',
 '009933',
 '00am',
 '01',
 '010',
 '0102',
 '010501c24f82',
 '01pm',
 '01t00',
 '01t04',
 '02',
 '0200',
 '0200a8c0',
 '0208201746330',
 '0208231900430',
 '0208240101180',
 '0209051816270',
 '0209091305070',
 '0209091538070',
 '0209172137100',
 '0209291337100',
 '0210020939580',
 '0210021830180',
 '02131',
 '024',
 '025',
 '029',
 '02e3',
 '02t09',
 '03',
 '0300',
 '03t04',
 '04',
 '040',
 '0400',
 '0410',
 '0455',
 '04t02',
 '05',
 '0500',
 '051',
 '0530',
 '05t03',
 '06',
 '0600',
 '06t02',
 '06t18',
 '07',
 '0700',
 '072',
 '0770',
 '07t03',
 '07t22',
 '08',
 '0800',
 '08039',
 '08pm',
 '08t03',
 '09',
 '0900',
 '09t03',
 '0a',
 '0a48',
 '0b1',
 '0b52',
 '0claws5',
 '0cm',
 '0e8a',
 '0fw',
 '0pt',
 '0px',
 '0x

In [33]:
selector = SelectKBest(chi2, k=300)

X_new = selector.fit_transform(X, y)
X_new

array([[ 0,  0,  0, ..., 12,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  5,  0, ...,  0,  5,  0],
       [ 0,  0,  0, ...,  0, 24,  0]])

In [34]:
cols = selector.get_support(indices=True)
cols
for i in cols :
    print(feature_list[i])

000
000000
000066
000080
0000ff
0700
0800
0cm
0pt
0px
100
10pt
120
20
210
211
219
22
2e
3c
3d
3d0
3darial
3dcenter
3e
550
61
81
8859
95
_blank
ad
ad_key
adclick
address
admanmail
admin
align
alt
amp
aol
arial
asp
background
bgcolor
black
blockquote
body
border
bordercolor
bottom
br
business
caramail
cash
cc0000
cellpadding
cellspacing
center
class
click
cn
color
colspan
content
credit
day
de
div
dollar
easydns
efi
egwn
email
equiv
exmh
ext
face
family
fax
ff0000
ffff99
ffffff
fill
financial
font
fork
form
free
freebsd
freshrpms
frugaljoe
gif
grant
guaranteed
guide
h3
head
height
helvetica
hidden
href
htm
html
ie
iiq
iiu
image
img
income
index
information
input
insiq
instruction
insurance
insuranceiq
internet
island
iso
jm
jp
jpg
justify
kingdom
left
legal
ler
lerami
lerctr
li
life
list
listinfo
listman
loan
mail
mail1
mailman
mailto
margin
marketing
marshall
membership
meta
microsoft
million
money
month
mortgage
mso
nalign
name
nbsp
ncellpadding
ncolor
ne
net
newnamedns
nface
nheight
n

In [35]:
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))  
X = vectorizer.fit_transform(documents).toarray()
X

array([[ 0,  0,  1, ...,  0,  0,  0],
       [ 3,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  1, ...,  0,  0,  0],
       ...,
       [ 4,  0,  4, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  5,  0,  0],
       [ 1,  0,  0, ..., 24,  0,  0]])

In [38]:
tfidfconverter = TfidfTransformer()  
X = tfidfconverter.fit_transform(X_new).toarray()
X

array([[0.        , 0.        , 0.        , ..., 0.29040979, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.11256093, 0.        , ..., 0.        , 0.0634832 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.3686312 ,
        0.        ]])

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [42]:
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)  
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1000, random_state=0)

In [43]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [44]:
y_test

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [46]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred)) 

[[517   1]
 [  2  91]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       518
           1       0.99      0.98      0.98        93

    accuracy                           1.00       611
   macro avg       0.99      0.99      0.99       611
weighted avg       1.00      1.00      1.00       611

0.9950900163666121
